### ISSUE TITLE
淘宝不支持旧商品id，调用淘宝的taobao.tbk.item.info.get接口时报错

### ISSUE THREAD

**Issue by 852438143** [pea-cake/tbk#10]
错误信息如下：
` 
{
    "code": 15,
    "msg": "Remote service error",
    "request_id": "16ke1b8qzvcuk",
    "sub_code": "-4003",
    "sub_msg": "您输入的商品ID不合法，请使用升级后的新商品ID，如有疑问请加入【淘宝联盟】线上合规升级咨询群（钉钉群：44965410）进行咨询"
  }
`

**Comment by pea-cake** [comment]
嗯，应该是商品id升级了，稍后看看

**Comment by pea-cake** [comment]
用关键词取代商品id的方法

**Comment by 852438143** [comment]
你好，新的接口新用户无法升级吗？ 钉钉群【淘宝联盟】线上合规升级咨询群-2群  里面很多新用户都无法升级。

**Comment by pea-cake** [comment]
那些新接口基本都需要订单量达到要求，才能申请使用，对普通玩家太不友好了，就是不想让你玩，我已经果断放弃了
