### ISSUE TITLE
nodemouble里有wechaty

### ISSUE THREAD

**Issue by TahmLi** [pea-cake/tbk#11]
但是npm run wechat后提示Cannot find module 'wechaty'

**Comment by pea-cake** [comment]
1.是不是，执行命令路径错了，在根路径下执行
2.删了node_modules重装试试

**Comment by TahmLi** [comment]
我删除了node_modules，用npm或cnpm或yarn安装，在node_modules中都会有wechaty的包,   npm run wechat就是找不到wechaty，有什么好办法吗
![image](https://user-images.githubusercontent.com/24243394/212348447-8a0d31ee-0c0a-4c98-bd3a-545dc8b312ef.png)

**Comment by pea-cake** [comment]
试试docker方式吧，最近有点忙了🥲

**Comment by TahmLi** [comment]
已解决
