### ISSUE TITLE
请问一下转链失败

### ISSUE THREAD

**Issue by XiaoAQWQ** [pea-cake/tbk#5]
请问一下转链报错这个是因为什么
应用权限除了淘口令预警及拦截查询以外全都申请过了
![image](https://user-images.githubusercontent.com/74170921/200725110-ad26d773-e710-4647-83b7-52533cc68c86.png)

**Comment by pea-cake** [comment]
1.先创建好推广位：https://pub.alimama.com/third/manage/record/site.htm?tab=traffic_purchasing  
<img width="800" alt="image" src="https://user-images.githubusercontent.com/58544092/200801651-fcc4870a-6405-4fd4-97af-ecd980ee6a5f.png">  
2.再创建应用：https://aff-open.taobao.com/developer/index.htm#/release/new  
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/58544092/200801847-138c6bf7-4ff5-4e61-9b41-69295c1aa89b.png">

**Comment by XiaoAQWQ** [comment]
重新添加了无自由阵地媒体备案，也添加了pid，然后再创建应用，依旧这样

**Comment by pea-cake** [comment]
修复了，新增一个配置TBconfig.adzone_id  
pid 'mm_123_456_789'的789就是adzone_id
