### ISSUE TITLE
数据库连接失败

### ISSUE THREAD

**Issue by ixuranran** [pea-cake/tbk#6]
### 数据库连接失败
已安装Mongo，创建了数据库‘’taobaoke“，系统会报下面的错误，麻烦大佬帮忙看一下
 E:\wxbot\tbk-main\wechat\db_action\index.js:39    
 const girls_table = mongoObj.dbase.collection(collection_name);                                  
^  TypeError: Cannot read properties of undefined (reading 'dbase')   
at selectData (E:\wxbot\tbk-main\wechat\db_action\index.js:39:34)     
at Object.selectCustomers (E:\wxbot\tbk-main\wechat\db_action\index.js:50:45)     
at E:\wxbot\tbk-main\utils\index.js:150:37  
Node.js v18.12.1

**Comment by XiaoAQWQ** [comment]
我也跟你同样问题，同样的配置在我本地机跑没问题，在腾讯云上就链接失败

**Comment by ixuranran** [comment]
# #

> 我也跟你同样问题，同样的配置在我本地机跑没问题，在腾讯云上就链接失败

是不是mogo环境的问题，能留个联系方式一块沟通一下吗

**Comment by pea-cake** [comment]
node 14, mongodb 5试试

**Comment by pea-cake** [comment]
node 14, mongodb 5试试

**Comment by ixuranran** [comment]
> 
node 14好像wechat直接起动不起来，node 18, mongodb 5 跟6 都报以上错误

**Comment by ixuranran** [comment]
> node 14, mongodb 5试试

node 14好像wechat直接起动不起来，node 18, mongodb 5 跟6 都报以上错误

**Comment by pea-cake** [comment]
node 16呢

**Comment by pea-cake** [comment]
node  v14
wechat报错那行，可以直接改源码
