### ISSUE TITLE
返回的优惠券都是无，是不是api有问题

### ISSUE THREAD

**Issue by ixuranran** [pea-cake/tbk#7]
返回的优惠券都是无，是不是代码有问题

**Comment by ixuranran** [comment]
淘宝回复：该商品暂无优惠和补贴，换一个试试
京东回复：【优惠券】：无

**Comment by pea-cake** [comment]
查查这个商品 https://item.m.jd.com/product/100025334303.html?&utm_source=iosapp&utm_medium=appshare&utm_campaign=t_335139774&utm_term=CopyURL&ad_od=share&gx=RnFgxTZROWLbn9RP--txW3CswyGyiHfjDpPI

**Comment by pea-cake** [comment]
【商品名】：雅迪（yadea）电动车DN2新国标电动自行车48V12AH铅酸长续航两轮电动车成人通勤小型轻便电瓶车 新塔夫绸白

【电商平台】：京东

【优惠券】：无

【预计补贴】：12.42

**Comment by ixuranran** [comment]
优惠券都是无，淘宝直接找不到优惠

**Comment by ixuranran** [comment]
> 【商品名】：雅迪（yadea）电动车DN2新国标电动自行车48V12AH铅酸长续航两轮电动车成人通勤小型轻便电瓶车 新塔夫绸白
> 
> 【电商平台】：京东
> 
> 【优惠券】：无
> 
> 【预计补贴】：12.42

这个也是显示优惠券 无

**Comment by pea-cake** [comment]
这正常的，就是没有优惠券，重要的是佣金（预计补贴）

**Comment by pea-cake** [comment]
看这个淘宝的商品【淘宝】https://m.tb.cn/h.UhOz91t?tk=dXoOdXORGjV CZ3457 「DOWNLAND微控温95白鹅绒被羽绒被四季被子保暖加厚冬被芯空调被」
点击链接直接打开 或者 淘宝搜索直接打开

**Comment by pea-cake** [comment]
【商品名】：downland微控温95白四季被子

【电商平台】：淘宝

【优惠券】：2300元 (满3499元减2300元)

【预计补贴】：95.62

【下单链接(或口令)】：
  ￥Au0EdXORgZm￥(复制淘口令到淘宝)
