### ISSUE TITLE
返利功能是不是还没做？

### ISSUE THREAD

**Issue by godJBJ** [pea-cake/tbk#8]
作者你好，我想请问一下这个返利功能是不是还没做？

**Comment by pea-cake** [comment]
没有自动返利  
用户购买商品后是需要回复**订单号**来绑定补贴订单的，绑定的订单在后台系统能查到  
自己再统一一个时间段，去给用户发补贴红包即可

**Comment by godJBJ** [comment]
哦哦，谢谢！还有一个问题，就是拼多多的接口测试调通了吗？我自己测试第一个接口没调通，这个pddSdk是自己封装的还是？谢谢作者~

**Comment by pea-cake** [comment]
拼多多pddSdk没问题，链接太长没处理，已修复
