### ISSUE TITLE
淘宝链接获取商品id是空的

### ISSUE THREAD

**Issue by zmxdd** [pea-cake/tbk#9]
大佬，使用链接获取的商品id是空的怎么解决，是因为最近淘宝升级商品id的缘故吗

**Comment by zmxdd** [comment]
![image](https://user-images.githubusercontent.com/119295472/204249052-d3758989-c812-4c36-b798-addfd508fd20.png)

**Comment by pea-cake** [comment]
商品链接来源是？淘宝app?天猫app?...

**Comment by zmxdd** [comment]
淘宝app

**Comment by zmxdd** [comment]
【淘宝】https://m.tb.cn/h.U7lg4A3?tk=sJtxd2L22HP CZ3457 「~床单单件冬季学生宿舍单人儿童1.5m水洗棉磨毛被单枕套三件套双人(~@ ~)」
点击链接直接打开 或者 淘宝搜索直接打开

**Comment by pea-cake** [comment]
不是所有商品都这样吧？

**Comment by zmxdd** [comment]
试了几个都不行，我不清楚有没有可以的，有以前测试的时候用过的链接吗

**Comment by pea-cake** [comment]
【淘宝】https://m.tb.cn/h.USy3luG?tk=W6Zjd2vqZyA CZ0001 「【新品】DOWNLAND轻盈铂优鹅绒被95白鹅绒冬被芯四季冬被子羽绒被」
点击链接直接打开 或者 淘宝搜索直接打开

**Comment by pea-cake** [comment]
商品的链接获取流程可以截图看看

**Comment by zmxdd** [comment]
![1669717349827](https://user-images.githubusercontent.com/119295472/204503825-37b435d7-f8fd-46c4-ac5b-ec7ad89185cc.jpg)

**Comment by zmxdd** [comment]
![1669717718312](https://user-images.githubusercontent.com/119295472/204505250-e6ac981d-be36-4301-8cdd-b940de87c2f9.jpg)

**Comment by zmxdd** [comment]
羽绒服那个链接可以正常读取

**Comment by pea-cake** [comment]
嗯，按照你说的方式，我这边也试了几个，没有出现id找不到的情况  
id是为了获取商品详情拿到商品的关键词，然后搜索关键词得到对应商品的推广信息。  
可能淘宝的部分商品已经升级了，这个后续再研究一下。

**Comment by zmxdd** [comment]
好的哥，Thanks♪(･ω･)ﾉ

**Comment by pea-cake** [comment]
用关键词取代商品id的方法
